export const userActions = [
  {
    "id": "ua001",
    "userOperationId": "cm2l2crxe000211dap3hmki8v",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_reservar",
    "userActionId": null,
    "description": "Reservar roupas para o casamento da Ana.",
    "notes": "Inclui vestido de gala e ternos para os padrinhos.",
    "scheduledAt": "2024-12-09T10:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "reservar|casamento|roupa",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua002",
    "userOperationId": "cm2l2crxe000211dap3hmki8v",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_provar",
    "userActionId": null,
    "description": "Provar roupas para o casamento da Ana.",
    "notes": "Teste de ajuste para vestido e ternos.",
    "scheduledAt": "2024-12-10T14:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "provar|casamento|vestido|terno",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua003",
    "userOperationId": "cm2l2crxe000211dap3hmki8v",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_retirar",
    "userActionId": null,
    "description": "Retirar roupas para o casamento da Ana.",
    "notes": "Retirada programada para dois dias antes do evento.",
    "scheduledAt": "2024-12-11T09:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "retirar|casamento|evento",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua004",
    "userOperationId": "cm2l2crxe000311dap3hmki8x",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_reservar",
    "userActionId": null,
    "description": "Reservar roupas para o baile de debutante da Carla.",
    "notes": "Vestido longo e acessórios para o evento.",
    "scheduledAt": "2024-12-09T15:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "reservar|debutante|vestido",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua005",
    "userOperationId": "cm2l2crxe000311dap3hmki8x",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_provar",
    "userActionId": null,
    "description": "Provar roupas para o baile de debutante da Carla.",
    "notes": "Verificação do ajuste das peças.",
    "scheduledAt": "2024-12-10T10:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "provar|debutante|evento",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua006",
    "userOperationId": "cm2l2crxe000311dap3hmki8x",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_retirar",
    "userActionId": null,
    "description": "Retirar roupas para o baile de debutante da Carla.",
    "notes": "Retirada planejada para o dia anterior ao evento.",
    "scheduledAt": "2024-12-11T11:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "retirar|debutante|festa",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua007",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_diagnosticar",
    "userActionId": null,
    "description": "Diagnosticar manutenção no carro do Marcos.",
    "notes": "Revisão geral para identificar problemas.",
    "scheduledAt": "2024-12-09T08:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "diagnosticar|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua008",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_orcar",
    "userActionId": null,
    "description": "Orçar manutenção no carro do Marcos.",
    "notes": "Definir os custos para a revisão geral.",
    "scheduledAt": "2024-12-10T09:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "orcar|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua009",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_executar",
    "userActionId": null,
    "description": "Executar manutenção no carro do Marcos.",
    "notes": "Troca de óleo e revisão do motor.",
    "scheduledAt": "2024-12-11T13:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "executar|manutenção|revisão",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  }
]
;
