export const userActions = [
  {
    "id": "ua001",
    "userOperationId": "cm2l2crxe000211dap3hmki8v",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_reservar",
    "userActionId": null,
    "description": "Reservar roupas para o casamento da Ana.",
    "notes": "Inclui vestido de gala e ternos para os padrinhos.",
    "scheduledAt": "2024-12-09T10:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "reservar|casamento|roupa",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua002",
    "userOperationId": "cm2l2crxe000211dap3hmki8v",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_provar",
    "userActionId": null,
    "description": "Provar roupas para o casamento da Ana.",
    "notes": "Teste de ajuste para vestido e ternos.",
    "scheduledAt": "2024-12-10T14:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "provar|casamento|vestido|terno",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua003",
    "userOperationId": "cm2l2crxe000211dap3hmki8v",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_retirar",
    "userActionId": null,
    "description": "Retirar roupas para o casamento da Ana.",
    "notes": "Retirada programada para dois dias antes do evento.",
    "scheduledAt": "2024-12-11T09:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "retirar|casamento|evento",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua004",
    "userOperationId": "cm2l2crxe000311dap3hmki8x",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_reservar",
    "userActionId": null,
    "description": "Reservar roupas para o baile de debutante da Carla.",
    "notes": "Vestido longo e acessórios para o evento.",
    "scheduledAt": "2024-12-09T15:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "reservar|debutante|vestido",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua005",
    "userOperationId": "cm2l2crxe000311dap3hmki8x",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_provar",
    "userActionId": null,
    "description": "Provar roupas para o baile de debutante da Carla.",
    "notes": "Verificação do ajuste das peças.",
    "scheduledAt": "2024-12-10T10:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "provar|debutante|evento",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua006",
    "userOperationId": "cm2l2crxe000311dap3hmki8x",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_retirar",
    "userActionId": null,
    "description": "Retirar roupas para o baile de debutante da Carla.",
    "notes": "Retirada planejada para o dia anterior ao evento.",
    "scheduledAt": "2024-12-11T11:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "retirar|debutante|festa",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua007",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_diagnosticar",
    "userActionId": null,
    "description": "Diagnosticar manutenção no carro do Marcos.",
    "notes": "Revisão geral para identificar problemas.",
    "scheduledAt": "2024-12-09T08:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "diagnosticar|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua008",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_orcar",
    "userActionId": null,
    "description": "Orçar manutenção no carro do Marcos.",
    "notes": "Definir os custos para a revisão geral.",
    "scheduledAt": "2024-12-10T09:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "orcar|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua009",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_executar",
    "userActionId": null,
    "description": "Executar manutenção no carro do Marcos.",
    "notes": "Troca de óleo e revisão do motor.",
    "scheduledAt": "2024-12-11T13:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "executar|manutenção|revisão",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua009",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_orcar",
    "userActionId": null,
    "description": "Elaborar orçamento para manutenção no carro do Marcos.",
    "notes": "Inclui troca de óleo e revisão geral do motor.",
    "scheduledAt": "2024-12-09T09:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": "300.00",
    "tags": "orçamento|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua009",
    "userOperationId": "cm2l2crxe000511dap3hmki8t",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_executar",
    "userActionId": null,
    "description": "Executar manutenção no carro do Marcos.",
    "notes": "Troca de óleo e verificação completa do motor.",
    "scheduledAt": "2024-12-10T13:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": "300.00",
    "tags": "executar|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua010",
    "userOperationId": "cm2l2crxe000611dap3hmki8q",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_diagnosticar",
    "userActionId": null,
    "description": "Diagnosticar reparo no ar-condicionado do carro do Pedro.",
    "notes": "Verificar funcionamento e identificar necessidade de reparos.",
    "scheduledAt": "2024-12-09T11:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "diagnosticar|ar-condicionado|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua011",
    "userOperationId": "cm2l2crxe000611dap3hmki8q",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_executar",
    "userActionId": null,
    "description": "Executar reparo no ar-condicionado do carro do Pedro.",
    "notes": "Troca de peças e recarga de gás.",
    "scheduledAt": "2024-12-10T10:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": "1200.00",
    "tags": "executar|reparo|ar-condicionado|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua012",
    "userOperationId": "cm2l2crxe000711dap3hmki8j",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_diagnosticar",
    "userActionId": null,
    "description": "Diagnosticar problemas nos freios do carro da Julia.",
    "notes": "Revisão completa do sistema de freios.",
    "scheduledAt": "2024-12-09T14:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "diagnosticar|freios|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua013",
    "userOperationId": "cm2l2crxe000711dap3hmki8j",
    "userClientId": "idProprietario02",
    "actionId": "sysOficinaCarro_executar",
    "userActionId": null,
    "description": "Executar substituição de pastilhas e discos de freio do carro da Julia.",
    "notes": "Inclui revisão do sistema hidráulico.",
    "scheduledAt": "2024-12-10T15:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": "850.00",
    "tags": "executar|freios|manutenção|carro",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua010",
    "userOperationId": "cm2l2crxe000411dap3hmki8w",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_reservar",
    "userActionId": null,
    "description": "Reservar roupas para o aniversário de 50 anos do João.",
    "notes": "Smoking e vestidos para o evento.",
    "scheduledAt": "2024-12-09T12:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "reservar|aniversário|vestido|terno",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua011",
    "userOperationId": "cm2l2crxe000411dap3hmki8w",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_provar",
    "userActionId": null,
    "description": "Provar roupas para o aniversário de 50 anos do João.",
    "notes": "Teste de ajuste para smoking e vestidos.",
    "scheduledAt": "2024-12-10T16:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "provar|aniversário|vestido|terno",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  },
  {
    "id": "ua012",
    "userOperationId": "cm2l2crxe000411dap3hmki8w",
    "userClientId": "idProprietario01",
    "actionId": "sysLocacaoRoupa_retirar",
    "userActionId": null,
    "description": "Retirar roupas para o aniversário de 50 anos do João.",
    "notes": "Retirada programada para dois dias antes do evento.",
    "scheduledAt": "2024-12-11T08:00:00",
    "executedAt": null,
    "finishedAt": null,
    "priceItems": null,
    "tags": "retirar|aniversário|festa",
    "active": true,
    "createAt": "2024-12-08T00:00:00",
    "updatedAt": "2024-12-08T00:00:00",
    "deletedAt": null
  }
]
;
